---
title: "analysis"
author: "Josef Klafka and Allyson Ettinger"
date: "1/22/2020"
output: html_document
---

```{r setup, include=FALSE}
require(tidyverse)
require(tidytext)
require(here)

knitr::opts_chunk$set(echo = TRUE)
```

```{r read results}
clean_results <- read_csv(here("Results/clean-results.csv"), 
                    col_names = c("Input", "Prediction", "Output", "Correct"))

noisy_results <- read_csv(here("Results/noisy-results.csv"), 
                    col_names = c("Input", "Prediction", "Output", "Correct"))

results %>% 
  clean_results %>% 
  bind_rows(noisy_results)
```

```{r plot proportion correct}
clean_results %>% 
  ggplot(aes(x = Correct)) + 
    geom_bar()

```

```{r analyzing what went wrong}
## how many words in common between prediction and output
predictions <- noisy_results %>%
  mutate(id = 1:n()) %>%
  select(id, Prediction) %>%
  unnest_tokens(word, Prediction)
  
outputs <- noisy_results %>%
  mutate(id = 1:n()) %>%
  select(id, Output) %>%
  unnest_tokens(word, Output)

predictions %>%
  left_join(outputs, by = "id") %>% 
  mutate(Correct = ifelse(word.x == word.y, 1, 0)) %>%
  group_by(id) %>%
  mutate(word_id = 1:n()) %>%
  summarize(Percent = sum(Correct) / max(word_id)) %>%
  
```